kind: ReplicaSet
apiVersion: apps/v1  
metadata:
   name: noders  
spec:
   replicas: 2 
   selector:
      matchLabels:
         app: node   
   template:
      metadata:
        name: nodeapp  
        labels:
          app: node   
      spec:
         imagePullSecrets:
         - name: dockerhublogin
         containers:  
         - name: nodeapp   
           image: mylandmarktech/nodejs-fe-app  
           ports:
           - containerPort: 9981
---
kind: Service
apiVersion: v1
metadata:
  name: nodesvc
spec:
  type: NodePort
  selector:
    app: node
  ports:
  - targetPort: 9981
    port: 80
    nodePort: 31500
