kind: Service  
apiVersion: v1     
metadata:
   name: hellosvc  
spec:
   type: ClusterIP  
   selector:
      run: hello  
   ports:
   - port: 80    
     targetPort: 80     
---  
kind: Service  
apiVersion: v1     
metadata:
   name: webappsvc  
spec:
   type: NodePort    
   selector:
      app: webapp  
   ports:
   - port: 80    
     targetPort: 8080   
     nodePort: 31000 # [30000 - 32676]  
